<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260209084931 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE championnat (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, equipe BOOLEAN NOT NULL, sport_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AB8C220AC78BCF8 ON championnat (sport_id)');
        $this->addSql('CREATE TABLE competition (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, championnat_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B50A2CB1627A0DA8 ON competition (championnat_id)');
        $this->addSql('CREATE TABLE epreuve (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE epreuve_competition (competition_id INT NOT NULL, epreuve_id INT NOT NULL, PRIMARY KEY (competition_id, epreuve_id))');
        $this->addSql('CREATE INDEX IDX_113EE93D7B39D312 ON epreuve_competition (competition_id)');
        $this->addSql('CREATE INDEX IDX_113EE93DAB990336 ON epreuve_competition (epreuve_id)');
        $this->addSql('CREATE TABLE nom_sport (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(30) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE sport (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, equipe BOOLEAN NOT NULL, nom_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1A85EFD2C8121CE9 ON sport (nom_id)');
        $this->addSql('ALTER TABLE championnat ADD CONSTRAINT FK_AB8C220AC78BCF8 FOREIGN KEY (sport_id) REFERENCES sport (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE competition ADD CONSTRAINT FK_B50A2CB1627A0DA8 FOREIGN KEY (championnat_id) REFERENCES championnat (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE epreuve_competition ADD CONSTRAINT FK_113EE93D7B39D312 FOREIGN KEY (competition_id) REFERENCES competition (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE epreuve_competition ADD CONSTRAINT FK_113EE93DAB990336 FOREIGN KEY (epreuve_id) REFERENCES epreuve (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sport ADD CONSTRAINT FK_1A85EFD2C8121CE9 FOREIGN KEY (nom_id) REFERENCES nom_sport (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE championnat DROP CONSTRAINT FK_AB8C220AC78BCF8');
        $this->addSql('ALTER TABLE competition DROP CONSTRAINT FK_B50A2CB1627A0DA8');
        $this->addSql('ALTER TABLE epreuve_competition DROP CONSTRAINT FK_113EE93D7B39D312');
        $this->addSql('ALTER TABLE epreuve_competition DROP CONSTRAINT FK_113EE93DAB990336');
        $this->addSql('ALTER TABLE sport DROP CONSTRAINT FK_1A85EFD2C8121CE9');
        $this->addSql('DROP TABLE championnat');
        $this->addSql('DROP TABLE competition');
        $this->addSql('DROP TABLE epreuve');
        $this->addSql('DROP TABLE epreuve_competition');
        $this->addSql('DROP TABLE nom_sport');
        $this->addSql('DROP TABLE sport');
    }
}
